# -*- coding: utf-8 -*-
"""
Created on Tue Mar  2 14:37:31 2021

@author: lcalv
******************************************************************************
***                                 GUI                                    ***
******************************************************************************
Module that just holds the messages that are shown when the
user hovers over the help buttons with the mouse. These messages have been 
defined apart from the gui.py so as to make the code more readable, given that,
distinct from the dialogs’ messages, they do not vary from one execution to another.
"""


class MessagesGui:
    INFO_SELECT_DATASET = 'Select a dataset for training the model. You can open the\n files by left clicking ' \
                          'and selecting "open file". '

    INFO_LOAD_FILES = 'Create a new model or select a model to use as father\n model. You xan select ' \
                      'created models\n by left clicking. '

    INFO_TRAIN_MODEL = 'For the model selected above, choose the number of topics\n that you want to use for training ' \
                       'and click\n train for proceeding. Training may take a little time. '

    INFO_SELECT_SUBMODEL = 'Select the model/submodel that you want to expand.'

    INFO_SELECT_TOPIC_TO_EXPAND = 'Select the topic belonging to the model/submodel selected above\n from which you ' \
                                  'want to create the submodel. The words belonging\n to a submodel will be those ' \
                                  'that belong to the chosen topic in the \n selected model/submodel. To proceed, ' \
                                  'select the number of topics \n you want to use for the training and click train ' \
                                  'submodel. '

    INFO_SHOW_DESCRIPTION = 'Select a model/submodel from which you want to see its description.\n You can see the ' \
                            'PLDAVIS diagram of the selected model on the right. '

    INFO_INSERT_DESCRIPTION = 'Select the model for which you want to insert\n the description for one or more of its ' \
                              'topics. '

    INFO_DELETE_SUBMODEL = 'Select the submodel you want to delete.\n For deleting ' \
                           'a model you must go to the second tab. '

    INFO_HTM_V1 = 'Hierarchical topic model in which the input documents that constitute the training corpus of the submodels '\
                  'are located from the second level in the hierarchy and onwards are generated by grouping the words that belong '\
                  'to a specific topic in the father model.'

    INFO_HTM_V2 = "Hierarchical topic model in which the input documents that constitute the training corpus of the submodels "\
                  "are located from the second level in the hierarchy and onwards are generated by grouping those documents' words "\
                  "from the original in which the representation of a specific topic in the father model reaches a certain threshold."

    INFO_DIAGNOSTICS = "Select the model/ubmodel from which you want to display diagnostics. These include some "\
                       "diagnostic measurements meaningful at the topic level, and some other at the level of individual words "\
                       "within topics. Once you have selected the model/submodel, click the 'See diagnostics' button and an "\
                       "interactive graph in which you can choose the measurements to display will be shown."

    SELECT_COMPARE = "Select the model/submodel from which you want to select one or more topics to compare."

    DRAG_COMPRARE = "By dragging topics from the top table to the bottom table you can compare them through a graph. "\
                    "To compare topics from different models/submodels, you need to select a model from the top "\
                    " view and drag it to the corresponding topic. Once you have desired topics to compare in "\
                    "the bottom table, you need to select the measurements to be represented in the x and the y axis, as "\
                    " well as the caption, title, and name for saving the plot. To proceed further"\
                    "click 'Plot' and the graph will be automatically depicted and saved simultaneously."
