# -*- coding: utf-8 -*-
"""
Created on Tue Mar  2 14:37:31 2021

@author: lcalv
"""


class MessagesGui:
    INFO_SELECT_DATASET = 'Select a dataset for training the model. You can open the\n files by left clicking with ' \
                          'the mouse and select open file. '

    INFO_LOAD_FILES = 'Create a new model or select a new model to use as father\n for the model. Once you have ' \
                      'create the model, you must\n click over one of the models in order to select it. '

    INFO_TRAIN_MODEL = 'For the model above selected, choose the number of topics\n that you want to use for training ' \
                       'the model, and then click\n train. Then wait until the model is trained. It may take a little. '

    INFO_SELECT_SUBMODEL = 'Select the model/submodel that you want to expand.'

    INFO_SELECT_TOPIC_TO_EXPAND = 'Select the topic belonging to the model/submodel above selected\n from which you ' \
                                  'want to create the submodel. The words belonging\n to a submodel will be those ' \
                                  'that belong to the chosen topic in the \n selected model/submodel. Then, ' \
                                  'select the number of topics to \n you want to use for the training and click train ' \
                                  'submodel. '

    INFO_SHOW_DESCRIPTION = 'Select a model/submodel from which you want to see its description.\n On the right you ' \
                            'can see a PLDAVIS diagram of the selected model. '

    INFO_INSERT_DESCRIPTION = 'Select the model for which you want to insert\n the description for one or more of its ' \
                              'topics. '

    INFO_DELETE_SUBMODEL = 'Select the submodel that you want to delete.\n For deleting ' \
                           'a model you must go to the second tab. '
    
    INFO_HTM_V1 = 'Hierarchical topic model in which the input documents that constitute the training corpus of the submodels '\
                  'located from the second level in the hierarchy and onwards are generated by grouping the words that belong '\
                  'to a specific topic in the father model.'
    
    INFO_HTM_V2 = "Hierarchical topic model in which the input documents that constitute the training corpus of the submodels "\
                  "located from the second level in the hierarchy and onwards are generated by grouping those documents' words "\
                  "from the original in which the representation of a specific topic in the father model reaches a certain threshold."
                  
    INFO_DIAGNOSTICS = "Select the model or submodel from which you want to display some of its diagnostics. These include some "\
                       "diagnostic measurements meaningful at the topic level, and some other at the level of individual words "\
                       "within topics. Once you have selected the model or submodel, click the 'See diagnostics' button and an "\
                       "interactive graph in which you can choose the measurements to display will be shown."
    
    SELECT_COMPARE = "Select the model or submodel from which you want to select one or more topics to compare."
    
    DRAG_COMPRARE = "By dragging topics from the top table to the bottom one you can compare them through a graph. "\
                    "To compare topics from different models/submodels, you just need to select a model from the top "\
                    " view and then drag the corresponding topic. Once you have all the topics you want to compare in "\
                    "the bottom table, you need to select the measurements to be represented in the x and the y axis, as "\
                    " well as the caption, title, and name for saving the plot. Having all the latter selected, you just "\
                    " need to click the button 'Plot' and the graph will be automatically depicted and saved simultaneously."

