# This file contains the complete list of options in the main script.
# It must contain at least a root menu with several options, and a description
# of each option in the root menu.
# Each option in any menu should have a description

# ##########################
# ROOT MENU
# ##########################
root:
  options: 
    #- setup
    - select_model
    - train_model
    - train_submodels
    - show_topic_model_description
    - delete_submodel
    - set_topic_description

# ##########################
# OPTIONS FROM THE ROOT MENU
# ##########################
create: 
  title: Create new results file
  post_opts:
    #- setup
    - select_model
    - train_model
    - train_submodels
    - show_topic_model_description
    - delete_submodel
    - set_topic_description
    
load:
  title: Load existing results file

#setup: 
#  title: Activate configuration file
  
select_model:
  title: Load an old model or create a new model

train_model:
  title: Train the selected model
  
train_submodels:
  title: Train one or more submodels

show_topic_model_description:
  title: See model/submodel's topic description

delete_submodel:
  title: Delete a submodel

set_topic_description:
  title: Give a name to describe the topics of a model


